# Generated by Django 4.0 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='record',
            field=models.CharField(choices=[('A', 'Add'), ('D', 'Delete'), ('C', 'Change')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='standard',
            field=models.CharField(choices=[('A', 'Standard'), ('B', 'Repo')], max_length=1),
        ),
    ]
